### 排序

In [2]:
import numpy as np

np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

y = np.sort(x)
print(y)

y = np.sort(x, axis=0)
print(y)

y = np.sort(x, axis=1)
print(y)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]
[[1.73 2.32 6.22 7.54 9.78]
 [5.17 6.93 8.25 9.28 9.76]
 [0.01 0.19 1.73 4.23 9.27]
 [0.88 4.29 4.97 7.32 7.99]
 [0.07 6.99 7.9  8.95 9.05]]
[[0.01 0.07 0.19 1.73 4.29]
 [2.32 4.23 0.88 1.73 6.22]
 [6.93 4.97 8.95 7.32 6.99]
 [7.99 5.17 9.28 7.9  8.25]
 [9.05 7.54 9.78 9.76 9.27]]
[[1.73 2.32 6.22 7.54 9.78]
 [5.17 6.93 8.25 9.28 9.76]
 [0.01 0.19 1.73 4.23 9.27]
 [0.88 4.29 4.97 7.32 7.99]
 [0.07 6.99 7.9  8.95 9.05]]


In [3]:
dt = np.dtype([('name', 'S10'), ('age', np.int)])
a = np.array([("Mike", 21), ("Nancy", 25), ("Bob", 17), ("Jane", 27)], dtype=dt)
b = np.sort(a, order='name')
print(b)

b = np.sort(a, order='age')
print(b)

[(b'Bob', 17) (b'Jane', 27) (b'Mike', 21) (b'Nancy', 25)]
[(b'Bob', 17) (b'Mike', 21) (b'Nancy', 25) (b'Jane', 27)]


- 从下面可以看出argsort函数返回的是数组值从小到大的索引值

In [4]:
np.random.seed(20200612)
x = np.random.randint(0, 10, 10)
print(x)

y = np.argsort(x)
print(y)

print(x[y])

y = np.argsort(-x)
print(y)

print(x[y])

[6 1 8 5 5 4 1 2 9 1]
[1 6 9 7 5 3 4 0 2 8]
[1 1 1 2 4 5 5 6 8 9]
[8 2 0 3 4 5 7 1 6 9]
[9 8 6 5 5 4 2 1 1 1]


In [5]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

y = np.argsort(x)
print(y)

y = np.argsort(x, axis=0)
print(y)

y = np.argsort(x, axis=1)
print(y)

y = np.array([np.take(x[i], np.argsort(x[i])) for i in range(5)])  
#numpy.take(a, indices, axis=None, out=None, mode='raise')沿轴从数组中获取元素。
print(y)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]
[[3 0 4 1 2]
 [1 0 4 2 3]
 [0 2 3 1 4]
 [2 4 1 3 0]
 [1 4 3 2 0]]
[[2 4 2 0 3]
 [0 2 3 2 0]
 [1 3 4 3 4]
 [3 1 1 4 1]
 [4 0 0 1 2]]
[[3 0 4 1 2]
 [1 0 4 2 3]
 [0 2 3 1 4]
 [2 4 1 3 0]
 [1 4 3 2 0]]
[[1.73 2.32 6.22 7.54 9.78]
 [5.17 6.93 8.25 9.28 9.76]
 [0.01 0.19 1.73 4.23 9.27]
 [0.88 4.29 4.97 7.32 7.99]
 [0.07 6.99 7.9  8.95 9.05]]


- 指定排序

In [6]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

index = np.lexsort([x[:, 0]])
print(index)

y = x[index]
print(y)

index = np.lexsort([-1 * x[:, 0]])
print(index)

y = x[index]
print(y)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]
[2 0 1 3 4]
[[0.01 4.23 0.19 1.73 9.27]
 [2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]
[4 3 1 0 2]
[[9.05 0.07 8.95 7.9  6.99]
 [7.99 4.97 0.88 7.32 4.29]
 [6.93 5.17 9.28 9.76 8.25]
 [2.32 7.54 9.78 1.73 6.22]
 [0.01 4.23 0.19 1.73 9.27]]


In [7]:
x = np.array([1, 5, 1, 4, 3, 4, 4])
y = np.array([9, 4, 0, 4, 0, 2, 1])
a = np.lexsort([x])
b = np.lexsort([y])
print(a)
print(x[a])

print(b)

print(y[b])

z = np.lexsort([y, x])
print(z)

print(x[z])

z = np.lexsort([x, y])
print(z)

print(y[z])

[0 2 4 3 5 6 1]
[1 1 3 4 4 4 5]
[2 4 6 5 1 3 0]
[0 0 1 2 4 4 9]
[2 0 4 6 5 3 1]
[1 1 3 4 4 4 5]
[2 4 6 5 3 1 0]
[0 0 1 2 4 4 9]


- 
```python
numpy.partition(a, kth, axis=-1, kind='introselect', order=None)
```
排序后第k个索引值对应的数拿出来当做partition，小于partition的放前面，大于partition的放后面(索引从0开始)

In [8]:
np.random.seed(100)
x = np.random.randint(1, 30, [8, 3])
print(x)

y = np.sort(x, axis=0)
print(y)

z = np.partition(x, kth=2, axis=0)
print(z)

[[ 9 25  4]
 [ 8 24 16]
 [17 11 21]
 [ 3 22  3]
 [ 3 15  3]
 [18 17 25]
 [16  5 12]
 [29 27 17]]
[[ 3  5  3]
 [ 3 11  3]
 [ 8 15  4]
 [ 9 17 12]
 [16 22 16]
 [17 24 17]
 [18 25 21]
 [29 27 25]]
[[ 3  5  3]
 [ 3 11  3]
 [ 8 15  4]
 [ 9 22 21]
 [17 24 16]
 [18 17 25]
 [16 25 12]
 [29 27 17]]


In [9]:
# 选取每一列第三小的数
np.random.seed(100)
x = np.random.randint(1, 30, [8, 3])
print(x)

z = np.partition(x, kth=2, axis=0)
print(z[2])
# 选取每一列第三大的数
np.random.seed(100)
x = np.random.randint(1, 30, [8, 3])
print(x)

z = np.partition(x, kth=-3, axis=0)
print(z[-3])

[[ 9 25  4]
 [ 8 24 16]
 [17 11 21]
 [ 3 22  3]
 [ 3 15  3]
 [18 17 25]
 [16  5 12]
 [29 27 17]]
[ 8 15  4]
[[ 9 25  4]
 [ 8 24 16]
 [17 11 21]
 [ 3 22  3]
 [ 3 15  3]
 [18 17 25]
 [16  5 12]
 [29 27 17]]
[17 24 17]


In [10]:
np.random.seed(100)
x = np.random.randint(1, 30, [8, 3])
print(x)

y = np.argsort(x, axis=0)
print(y)

z = np.argpartition(x, kth=2, axis=0)
print(z)

[[ 9 25  4]
 [ 8 24 16]
 [17 11 21]
 [ 3 22  3]
 [ 3 15  3]
 [18 17 25]
 [16  5 12]
 [29 27 17]]
[[3 6 3]
 [4 2 4]
 [1 4 0]
 [0 5 6]
 [6 3 1]
 [2 1 7]
 [5 0 2]
 [7 7 5]]
[[3 6 3]
 [4 2 4]
 [1 4 0]
 [0 3 2]
 [2 1 1]
 [5 5 5]
 [6 0 6]
 [7 7 7]]


In [12]:
# 选取每一列第三小的数的索引
np.random.seed(100)
x = np.random.randint(1, 30, [8, 3])
print(x)

z = np.argpartition(x, kth=2, axis=0)
print(z[2])

# 选取每一列第三大的数的索引
np.random.seed(100)
x = np.random.randint(1, 30, [8, 3])
print(x)

z = np.argpartition(x, kth=-3, axis=0)
print(z[-3])

[[ 9 25  4]
 [ 8 24 16]
 [17 11 21]
 [ 3 22  3]
 [ 3 15  3]
 [18 17 25]
 [16  5 12]
 [29 27 17]]
[1 4 0]
[[ 9 25  4]
 [ 8 24 16]
 [17 11 21]
 [ 3 22  3]
 [ 3 15  3]
 [18 17 25]
 [16  5 12]
 [29 27 17]]
[2 1 7]


### 搜索

In [13]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

y = np.argmax(x)
print(y)

y = np.argmax(x, axis=0)
print(y)

y = np.argmax(x, axis=1)
print(y)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]
2
[4 0 0 1 2]
[2 3 4 0 0]


In [14]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

y = np.argmin(x)
print(y)

y = np.argmin(x, axis=0)
print(y)

y = np.argmin(x, axis=1)
print(y)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]
10
[2 4 2 0 3]
[3 1 0 2 1]


In [15]:
x = np.array([0, 2, 3])
print(x)  # [0 2 3]
print(x.shape)  # (3,)
print(x.ndim)  # 1

y = np.nonzero(x)
print(y)  # (array([1, 2], dtype=int64),)
print(np.array(y))  # [[1 2]]
print(np.array(y).shape)  # (1, 2)
print(np.array(y).ndim)  # 2
print(np.transpose(y))

print(x[np.nonzero(x)])

[0 2 3]
(3,)
1
(array([1, 2], dtype=int64),)
[[1 2]]
(1, 2)
2
[[1]
 [2]]
[2 3]


In [16]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)

print(x.shape)  # (3, 3)
print(x.ndim)  # 2

y = np.nonzero(x)
print(y)

print(np.array(y))

print(np.array(y).shape)  # (2, 4)
print(np.array(y).ndim)  # 2

y = x[np.nonzero(x)]
print(y)  # [3 4 5 6]

y = np.transpose(np.nonzero(x))
print(y)

[[3 0 0]
 [0 4 0]
 [5 6 0]]
(3, 3)
2
(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))
[[0 1 2 2]
 [0 1 0 1]]
(2, 4)
2
[3 4 5 6]
[[0 0]
 [1 1]
 [2 0]
 [2 1]]


In [17]:
x = np.array([[[0, 1], [1, 0]], [[0, 1], [1, 0]], [[0, 0], [1, 0]]])
print(x)

print(np.shape(x))  # (3, 2, 2)
print(x.ndim)  # 3

y = np.nonzero(x)
print(np.array(y))

print(np.array(y).shape)  # (3, 5)
print(np.array(y).ndim)  # 2
print(y)

print(x[np.nonzero(x)])

[[[0 1]
  [1 0]]

 [[0 1]
  [1 0]]

 [[0 0]
  [1 0]]]
(3, 2, 2)
3
[[0 0 1 1 2]
 [0 1 0 1 1]
 [1 0 1 0 0]]
(3, 5)
2
(array([0, 0, 1, 1, 2], dtype=int64), array([0, 1, 0, 1, 1], dtype=int64), array([1, 0, 1, 0, 0], dtype=int64))
[1 1 1 1 1]


In [18]:
x = np.arange(10)
print(x)

y = np.where(x < 5, x, 10 * x)
print(y)

x = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
y = np.where(x < 4, x, -1)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]
[[ 0  1  2]
 [ 0  2 -1]
 [ 0  3 -1]]


In [19]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.where(x > 5)
print(y)

print(x[y])

y = np.nonzero(x > 5)
print(y)

print(x[y])


x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.where(x > 25)
print(y)

print(x[y])

y = np.nonzero(x > 25)
print(y)

print(x[y])

(array([5, 6, 7], dtype=int64),)
[6 7 8]
(array([5, 6, 7], dtype=int64),)
[6 7 8]
(array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))
[26 27 28 29 30 31 32 33 34 35]
(array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))
[26 27 28 29 30 31 32 33 34 35]


- searchsorted 应该插入的索引

In [20]:
x = np.array([0, 1, 5, 9, 11, 18, 26, 33])
y = np.searchsorted(x, 15)
print(y)  # 5

y = np.searchsorted(x, 15, side='right')
print(y)  # 5

y = np.searchsorted(x, -1)
print(y)  # 0

y = np.searchsorted(x, -1, side='right')
print(y)  # 0

y = np.searchsorted(x, 35)
print(y)  # 8

y = np.searchsorted(x, 35, side='right')
print(y)  # 8

y = np.searchsorted(x, 11)
print(y)  # 4

y = np.searchsorted(x, 11, side='right')
print(y)  # 5

y = np.searchsorted(x, 0)
print(y)  # 0

y = np.searchsorted(x, 0, side='right')
print(y)  # 1

y = np.searchsorted(x, 33)
print(y)  # 7

y = np.searchsorted(x, 33, side='right')
print(y)

5
5
0
0
8
8
4
5
0
1
7
8


In [21]:
x = np.array([0, 1, 5, 9, 11, 18, 26, 33])
y = np.searchsorted(x, [-1, 0, 11, 15, 33, 35])
print(y)

y = np.searchsorted(x, [-1, 0, 11, 15, 33, 35], side='right')
print(y)

[0 0 4 5 7 8]
[0 1 5 5 8 8]


In [22]:
x = np.array([0, 1, 5, 9, 11, 18, 26, 33])
np.random.shuffle(x)
print(x)

x_sort = np.argsort(x)
print(x_sort)

y = np.searchsorted(x, [-1, 0, 11, 15, 33, 35], sorter=x_sort)
print(y)

y = np.searchsorted(x, [-1, 0, 11, 15, 33, 35], side='right', sorter=x_sort)
print(y)

[ 1  0 26  9 33 11 18  5]
[1 0 7 3 5 6 2 4]
[0 0 4 5 7 8]
[0 1 5 5 8 8]


### 计数

In [23]:
x = np.count_nonzero(np.eye(4))
print(x)

x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]])
print(x)

x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]], axis=0)
print(x)

x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]], axis=1)
print(x)

4
5
[1 1 1 1 1]
[2 3]


### 集合

In [2]:
import numpy as np
x = np.unique([1, 1, 3, 2, 3, 3])
print(x)

x = sorted(set([1, 1, 3, 2, 3, 3]))
print(x)

x = np.array([[1, 1], [2, 3]])
u = np.unique(x)
print(u)

x = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
y = np.unique(x, axis=0)
print(y)

x = np.array(['a', 'b', 'b', 'c', 'a'])
u, index = np.unique(x, return_index=True)
print(u)
print(index)
print(x[index]) 

x = np.array([1, 2, 6, 4, 2, 3, 2])
u, index = np.unique(x, return_inverse=True)
print(u)
print(index)
print(u[index])

u, count = np.unique(x, return_counts=True)
print(u)
print(count) 

[1 2 3]
[1, 2, 3]
[1 2 3]
[[1 0 0]
 [2 3 4]]
['a' 'b' 'c']
[0 1 3]
['a' 'b' 'c']
[1 2 3 4 6]
[0 1 4 3 1 2 1]
[1 2 6 4 2 3 2]
[1 2 3 4 6]
[1 3 1 1 1]


- 布尔运算

In [3]:
# 包含
test = np.array([0, 1, 2, 5, 0])
states = [0, 2]
mask = np.in1d(test, states)
print(mask) 
print(test[mask]) 

mask = np.in1d(test, states, invert=True)
print(mask)
print(test[mask])

[ True False  True False  True]
[0 2 0]
[False  True False  True False]
[1 5]


In [4]:
from functools import reduce
# 交集
x = np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])
print(x)  # [1 3]

x = np.array([1, 1, 2, 3, 4])
y = np.array([2, 1, 4, 6])
xy, x_ind, y_ind = np.intersect1d(x, y, return_indices=True)
print(x_ind)  # [0 2 4]
print(y_ind)  # [1 0 2]
print(xy)  # [1 2 4]
print(x[x_ind])  # [1 2 4]
print(y[y_ind])  # [1 2 4]

x = reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
print(x)

[1 3]
[0 2 4]
[1 0 2]
[1 2 4]
[1 2 4]
[1 2 4]
[3]


In [5]:
# 并集
x = np.union1d([-1, 0, 1], [-2, 0, 2])
print(x)
x = reduce(np.union1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
print(x)

[-2 -1  0  1  2]
[1 2 3 4 6]


In [6]:
# 差集
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
x = np.setdiff1d(a, b)
print(x) 

[1 2]


- 集合的对称差，即两个集合的交集的补集

In [7]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
x = np.setxor1d(a, b)
print(x) 

[1 2 5 6]
