### Numpy的广播机制

广播规则：<br>
- 维度不一致时，维度从后往前第一个维度相同，后面的直接补齐
- 维度不一致，若有一个矩阵存在维度为1，直接触发广播
- 维度一致时，对应元素发生相应操作
- 广播就是把长度不够的向量按最长的向量补齐

In [2]:
import numpy as np

A = np.zeros((2,5,3,4))
B = np.zeros((3))
# print((A+B).shape)
# 直接报错

A = np.zeros((2,5,3,4))
B = np.zeros((4))
print((A+B).shape)

(2, 5, 3, 4)


In [3]:
x = np.arange(4).reshape(4, 1)
y = np.ones(5)

print(x.shape)
print(y.shape)

print((x + y).shape)
print(x + y)

x = np.array([0.0, 10.0, 20.0, 30.0])
y = np.array([1.0, 2.0, 3.0])
z = x[:, np.newaxis] + y
print(z)

(4, 1)
(5,)
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


### 运算

In [4]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = x + 1
print(y)
print(np.add(x, 1))

y = x - 1
print(y)
print(np.subtract(x, 1))

y = x * 2
print(y)
print(np.multiply(x, 2))

y = x / 2
print(y)
print(np.divide(x, 2))

y = x // 2
print(y)
print(np.floor_divide(x, 2))

y = x ** 2
print(y)
print(np.power(x, 2))

[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
[ 2  4  6  8 10 12 14 16]
[ 2  4  6  8 10 12 14 16]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[0 1 1 2 2 3 3 4]
[0 1 1 2 2 3 3 4]
[ 1  4  9 16 25 36 49 64]
[ 1  4  9 16 25 36 49 64]


In [5]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = x + 1
print(y)
print(np.add(x, 1))

y = x - 1
print(y)
print(np.subtract(x, 1))

y = x * 2
print(y)
print(np.multiply(x, 2))

y = x / 2
print(y)
print(np.divide(x, 2))

y = x // 2
print(y)
print(np.floor_divide(x, 2))

y = x ** 2
print(y)
print(np.power(x, 2))

[[12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]
 [32 33 34 35 36]]
[[12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]
 [32 33 34 35 36]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]
[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]
 [62 64 66 68 70]]
[[ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [10.5 11.  11.5 12.  12.5]
 [13.  13.5 14.  14.5 15. ]
 [15.5 16.  16.5 17.  17.5]]
[[ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [10.5 11.  11.5 12.  12.5]
 [13.  13.5 14.  14.5 15. ]
 [15.5 16.  16.5 17.  17.5]]
[[ 5  6  6  7  7]
 [ 8  8  9  9 10]
 [10 11 11 12 12]
 [13 13 14 14 15]
 [15 16 16 17 17]]
[[ 5  6  6  7  7]
 [ 8  8  9  9 10]
 [10 11 11 12 12]
 [13 13 14 14 15]
 [15 16 1

In [6]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])

y = np.arange(1, 6)
print(y)

z = x + y
print(z)
print(np.add(x, y))

z = x - y
print(z)
print(np.subtract(x, y))

z = x * y
print(z)
print(np.multiply(x, y))

z = x / y
print(z)
print(np.divide(x, y))

z = x // y
print(z)
print(np.floor_divide(x, y))

z = x ** np.full([1, 5], 2)
print(z)
print(np.power(x, np.full([5, 5], 2)))

[1 2 3 4 5]
[[12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]
 [27 29 31 33 35]
 [32 34 36 38 40]]
[[12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]
 [27 29 31 33 35]
 [32 34 36 38 40]]
[[10 10 10 10 10]
 [15 15 15 15 15]
 [20 20 20 20 20]
 [25 25 25 25 25]
 [30 30 30 30 30]]
[[10 10 10 10 10]
 [15 15 15 15 15]
 [20 20 20 20 20]
 [25 25 25 25 25]
 [30 30 30 30 30]]
[[ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]
 [ 26  54  84 116 150]
 [ 31  64  99 136 175]]
[[ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]
 [ 26  54  84 116 150]
 [ 31  64  99 136 175]]
[[11.          6.          4.33333333  3.5         3.        ]
 [16.          8.5         6.          4.75        4.        ]
 [21.         11.          7.66666667  6.          5.        ]
 [26.         13.5         9.33333333  7.25        6.        ]
 [31.         16.         11.          8.5         7.        ]]
[[11.          6.          4.33333333  3.5         3.        ]
 [16.        

In [7]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])

y = np.arange(1, 26).reshape([5, 5])
print(y)

z = x + y
print(z)
print(np.add(x, y))

z = x - y
print(z)
print(np.subtract(x, y))

z = x * y
print(z)
print(np.multiply(x, y))

z = x / y
print(z)
print(np.divide(x, y))

z = x // y
print(z)
print(np.floor_divide(x, y))

z = x ** np.full([5, 5], 2)
print(z)
print(np.power(x, np.full([5, 5], 2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]
[[12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]
 [231 264 299 336 375]
 [416 459 504 551 600]
 [651 704 759 816 875]]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]
 [231 264 299 336 375]
 [416 459 504 551 600]
 [651 704 759 816 875]]
[[11.          6.          4.33333333  3.5         3.        ]
 [ 2.66666667  2.42857143  2.25        2.11111111  2.        ]
 [ 1.90909091  1.83333333  1.76923077  1.71428571  1.66666667]
 [ 1.625       1.58823529  1.55555556  1.52631579  1.5       ]
 [ 1.47619048  1.45454545  1.43478261  1.41666667  1.4       

In [8]:
x = np.arange(1, 5)
print(x)

y = np.sqrt(x)
print(y)

print(np.power(x, 0.5))

y = np.square(x)
print(y)

print(np.power(x, 2))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[1.         1.41421356 1.73205081 2.        ]
[ 1  4  9 16]
[ 1  4  9 16]


### 三角函数

In [9]:
x = np.linspace(start=0, stop=np.pi / 2, num=10)
print(x)

y = np.sin(x)
print(y)

z = np.arcsin(y)
print(z)

y = np.cos(x)
print(y)

z = np.arccos(y)
print(z)

y = np.tan(x)
print(y)

z = np.arctan(y)

[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
[0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
 0.8660254  0.93969262 0.98480775 1.        ]
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
[1.00000000e+00 9.84807753e-01 9.39692621e-01 8.66025404e-01
 7.66044443e-01 6.42787610e-01 5.00000000e-01 3.42020143e-01
 1.73648178e-01 6.12323400e-17]
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
[0.00000000e+00 1.76326981e-01 3.63970234e-01 5.77350269e-01
 8.39099631e-01 1.19175359e+00 1.73205081e+00 2.74747742e+00
 5.67128182e+00 1.63312394e+16]


### 指数和对数

In [10]:
x = np.arange(1, 5)
print(x)

y = np.exp(x)
print(y)

z = np.log(y)
print(z)

[1 2 3 4]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1. 2. 3. 4.]


### 加法和乘法

In [12]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.sum(x)
print(y)

y = np.sum(x, axis=0)
print(y)

y = np.sum(x, axis=1)

x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.cumsum(x)
print(y)

y = np.cumsum(x, axis=0)
print(y)

y = np.cumsum(x, axis=1)
print(y)

575
[105 110 115 120 125]
[ 11  23  36  50  65  81  98 116 135 155 176 198 221 245 270 296 323 351
 380 410 441 473 506 540 575]
[[ 11  12  13  14  15]
 [ 27  29  31  33  35]
 [ 48  51  54  57  60]
 [ 74  78  82  86  90]
 [105 110 115 120 125]]
[[ 11  23  36  50  65]
 [ 16  33  51  70  90]
 [ 21  43  66  90 115]
 [ 26  53  81 110 140]
 [ 31  63  96 130 165]]


In [13]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.prod(x)
print(y)

y = np.prod(x, axis=0)
print(y)

y = np.prod(x, axis=1)
print(y)

x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.cumprod(x)
print(y)

y = np.cumprod(x, axis=0)
print(y)

y = np.cumprod(x, axis=1)
print(y)

788529152
[2978976 3877632 4972968 6294624 7875000]
[  360360  1860480  6375600 17100720 38955840]
[         11         132        1716       24024      360360     5765760
    98017920  1764322560  -837609728   427674624   391232512    17180672
   395155456   893796352   870072320  1147043840   905412608  -418250752
   755630080  1194065920 -1638662144  -897581056   444596224 -2063597568
   788529152]
[[     11      12      13      14      15]
 [    176     204     234     266     300]
 [   3696    4488    5382    6384    7500]
 [  96096  121176  150696  185136  225000]
 [2978976 3877632 4972968 6294624 7875000]]
[[      11      132     1716    24024   360360]
 [      16      272     4896    93024  1860480]
 [      21      462    10626   255024  6375600]
 [      26      702    19656   570024 17100720]
 [      31      992    32736  1113024 38955840]]


### 其他数学函数

In [14]:
A = np.arange(2, 14).reshape((3, 4))
A[1, 1] = 8
print(A)

print(np.diff(A))

print(np.diff(A, axis=0))

[[ 2  3  4  5]
 [ 6  8  8  9]
 [10 11 12 13]]
[[1 1 1]
 [2 0 1]
 [1 1 1]]
[[4 5 4 4]
 [4 3 4 4]]


In [15]:
x = np.random.rand(3, 3) * 10
print(x)

y = np.around(x)
print(y)

y = np.around(x, decimals=2)
print(y)

[[6.10290695 0.43632229 0.09020237]
 [4.05938565 5.20866281 9.86853097]
 [2.94446417 3.1202986  8.94525045]]
[[ 6.  0.  0.]
 [ 4.  5. 10.]
 [ 3.  3.  9.]]
[[6.1  0.44 0.09]
 [4.06 5.21 9.87]
 [2.94 3.12 8.95]]


In [16]:
x = np.random.rand(3, 3) * 10
print(x)

y = np.ceil(x)
print(y)

y = np.floor(x)
print(y)

[[3.95786091 5.77345462 5.19117142]
 [2.34611134 0.31311503 7.05699902]
 [6.36401624 2.71033934 5.30433789]]
[[4. 6. 6.]
 [3. 1. 8.]
 [7. 3. 6.]]
[[3. 5. 5.]
 [2. 0. 7.]
 [6. 2. 5.]]


In [17]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = np.clip(x, a_min=20, a_max=30)
print(y)

[[20 20 20 20 20]
 [20 20 20 20 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [30 30 30 30 30]]


In [18]:
x = np.arange(-5, 5)
print(x)

y = np.abs(x)
print(y)

y = np.absolute(x)
print(y)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[5 4 3 2 1 0 1 2 3 4]
[5 4 3 2 1 0 1 2 3 4]


In [19]:
x = np.arange(-5, 5)
print(x)

print(np.sign(x))

[-5 -4 -3 -2 -1  0  1  2  3  4]
[-1 -1 -1 -1 -1  0  1  1  1  1]


### 逻辑函数

In [21]:
np.all(np.nan)

True

In [22]:
a = np.array([0, 4, 5])
b = np.copy(a)
print(np.all(a == b))
print(np.any(a == b))

b[0] = 1
print(np.all(a == b))
print(np.any(a == b))

print(np.all([1.0, np.nan]))
print(np.any([1.0, np.nan]))

a = np.eye(3)
print(np.all(a, axis=0))
print(np.any(a, axis=0))

True
True
False
True
True
True
[False False False]
[ True  True  True]


In [23]:
a=np.array([1,2,np.nan])
print(np.isnan(a))

[False False  True]


### 逻辑运算

In [24]:
print(np.logical_not(3))  

print(np.logical_not([True, False, 0, 1]))

x = np.arange(5)
print(np.logical_not(x < 3))

False
[False  True  True False]
[False False False  True  True]


In [25]:
print(np.logical_and(True, False))  

# true & true, false & false
print(np.logical_and([True, False], [True, False]))

print(np.logical_and(x > 1, x < 4))

False
[ True False]
[False False  True  True False]


In [26]:
print(np.logical_or(True, False))

print(np.logical_or([True, False], [False, False]))

print(np.logical_or(x < 1, x > 3))

True
[ True False]
[ True False False False  True]


In [27]:
# 异或运算，同为假，异为真
print(np.logical_xor(True, False))
# True
print(np.logical_xor([True, True, False, False], [True, False, True, False]))
# [False  True  True False]
print(np.logical_xor(x < 1, x > 3))
# [ True False False False  True]
print(np.logical_xor(0, np.eye(2)))

True
[False  True  True False]
[ True False False False  True]
[[ True False]
 [False  True]]


In [28]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

y = x > 2
print(y)
print(np.greater(x, 2))

y = x >= 2
print(y)
print(np.greater_equal(x, 2))

y = x == 2
print(y)
print(np.equal(x, 2))

y = x != 2
print(y)
print(np.not_equal(x, 2))

y = x < 2
print(y)
print(np.less(x, 2))

y = x <= 2
print(y)
print(np.less_equal(x, 2))

[False False  True  True  True  True  True  True]
[False False  True  True  True  True  True  True]
[False  True  True  True  True  True  True  True]
[False  True  True  True  True  True  True  True]
[False  True False False False False False False]
[False  True False False False False False False]
[ True False  True  True  True  True  True  True]
[ True False  True  True  True  True  True  True]
[ True False False False False False False False]
[ True False False False False False False False]
[ True  True False False False False False False]
[ True  True False False False False False False]


In [29]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = x > 20
print(y)
print(np.greater(x, 20))

y = x >= 20
print(y)
print(np.greater_equal(x, 20))

y = x == 20
print(y)
print(np.equal(x, 20))

y = x != 20
print(y)
print(np.not_equal(x, 20))

y = x < 20
print(y)
print(np.less(x, 20))

y = x <= 20
print(y)
print(np.less_equal(x, 20))

[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False False False False]
 [False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False False False False]
 [False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False False False False]
 [False False False False  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[False False False False False]
 [False False False False  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[ T

In [30]:
np.random.seed(20200611)
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])

y = np.random.randint(10, 40, [5, 5])
print(y)

z = x > y
print(z)
print(np.greater(x, y))

z = x >= y
print(z)
print(np.greater_equal(x, y))

z = x == y
print(z)
print(np.equal(x, y))

z = x != y
print(z)
print(np.not_equal(x, y))

z = x < y
print(z)
print(np.less(x, y))

z = x <= y
print(z)
print(np.less_equal(x, y))

[[32 28 31 33 37]
 [23 37 37 30 29]
 [32 24 10 33 15]
 [27 17 10 36 16]
 [25 32 23 39 34]]
[[False False False False False]
 [False False False False False]
 [False False  True False  True]
 [False  True  True False  True]
 [ True False  True False  True]]
[[False False False False False]
 [False False False False False]
 [False False  True False  True]
 [False  True  True False  True]
 [ True False  True False  True]]
[[False False False False False]
 [False False False False False]
 [False False  True False  True]
 [False  True  True False  True]
 [ True  True  True False  True]]
[[False False False False False]
 [False False False False False]
 [False False  True False  True]
 [False  True  True False  True]
 [ True  True  True False  True]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True False False False]]
[[False False False False False]
 [False False False False False]
 [False False

In [31]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])

np.random.seed(20200611)
y = np.random.randint(10, 50, 5)

print(y)

z = x > y
print(z)
print(np.greater(x, y))

z = x >= y
print(z)
print(np.greater_equal(x, y))

z = x == y
print(z)
print(np.equal(x, y))

z = x != y
print(z)
print(np.not_equal(x, y))

z = x < y
print(z)
print(np.less(x, y))

z = x <= y
print(z)
print(np.less_equal(x, y))

[32 37 30 24 10]
[[False False False False  True]
 [False False False False  True]
 [False False False False  True]
 [False False False  True  True]
 [False False  True  True  True]]
[[False False False False  True]
 [False False False False  True]
 [False False False False  True]
 [False False False  True  True]
 [False False  True  True  True]]
[[False False False False  True]
 [False False False False  True]
 [False False False  True  True]
 [False False False  True  True]
 [False False  True  True  True]]
[[False False False False  True]
 [False False False False  True]
 [False False False  True  True]
 [False False False  True  True]
 [False False  True  True  True]]
[[False False False False False]
 [False False False False False]
 [False False False  True False]
 [False False False False False]
 [False False False False False]]
[[False False False False False]
 [False False False False False]
 [False False False  True False]
 [False False False False False]
 [False False False F

In [32]:
x = np.isclose([1e10, 1e-7], [1.00001e10, 1e-8])
print(x)

x = np.allclose([1e10, 1e-7], [1.00001e10, 1e-8])
print(x)

x = np.isclose([1e10, 1e-8], [1.00001e10, 1e-9])
print(x)

x = np.allclose([1e10, 1e-8], [1.00001e10, 1e-9])
print(x)

x = np.isclose([1e10, 1e-8], [1.0001e10, 1e-9])
print(x)

x = np.allclose([1e10, 1e-8], [1.0001e10, 1e-9])
print(x)

x = np.isclose([1.0, np.nan], [1.0, np.nan])
print(x)

x = np.allclose([1.0, np.nan], [1.0, np.nan])
print(x)

x = np.isclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)
print(x)

x = np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)
print(x)

[ True False]
False
[ True  True]
True
[False  True]
False
[ True False]
False
[ True  True]
True
