### numpy中的常量

In [1]:
import numpy as np

In [5]:
constant = [np.nan,np.inf,np.pi,np.e]
print(constant)

[nan, inf, 3.141592653589793, 2.718281828459045]


### datetime64

In [6]:
a = np.datetime64('2020-03-01')
print(a, a.dtype)  # 2020-03-01 datetime64[D]

a = np.datetime64('2020-03')
print(a, a.dtype)  # 2020-03 datetime64[M]

a = np.datetime64('2020-03-08 20:00:05')
print(a, a.dtype)  # 2020-03-08T20:00:05 datetime64[s]

a = np.datetime64('2020-03-08 20:00')
print(a, a.dtype)  # 2020-03-08T20:00 datetime64[m]

a = np.datetime64('2020-03-08 20')
print(a, a.dtype)  # 2020-03-08T20 datetime64[h]

2020-03-01 datetime64[D]
2020-03 datetime64[M]
2020-03-08T20:00:05 datetime64[s]
2020-03-08T20:00 datetime64[m]
2020-03-08T20 datetime64[h]


- 单位不同的时间但很可能是一样的，3月等于3月1号

In [7]:
a = np.datetime64('2020-03', 'D')
print(a, a.dtype)  # 2020-03-01 datetime64[D]

a = np.datetime64('2020-03', 'Y')
print(a, a.dtype)  # 2020 datetime64[Y]

print(np.datetime64('2020-03') == np.datetime64('2020-03-01'))  # True
print(np.datetime64('2020-03') == np.datetime64('2020-03-02'))  #False

2020-03-01 datetime64[D]
2020 datetime64[Y]
True
False


- 时间范围

In [8]:
a = np.arange('2020-08-01', '2020-08-10', dtype=np.datetime64)
print(a)

['2020-08-01' '2020-08-02' '2020-08-03' '2020-08-04' '2020-08-05'
 '2020-08-06' '2020-08-07' '2020-08-08' '2020-08-09']


- 时间差

In [9]:
a = np.datetime64('2020-03-08') - np.datetime64('2020-03-07')
b = np.datetime64('2020-03-08') - np.datetime64('202-03-07 08:00')
c = np.datetime64('2020-03-08') - np.datetime64('2020-03-07 23:00', 'D')

print(a, a.dtype)  # 1 days timedelta64[D]
print(b, b.dtype)  # 956178240 minutes timedelta64[m]
print(c, c.dtype)  # 1 days timedelta64[D]

a = np.datetime64('2020-03') + np.timedelta64(20, 'D')
b = np.datetime64('2020-06-15 00:00') + np.timedelta64(12, 'h')
print(a, a.dtype)  # 2020-03-21 datetime64[D]
print(b, b.dtype)  # 2020-06-15T12:00 datetime64[m]

1 days timedelta64[D]
956178240 minutes timedelta64[m]
1 days timedelta64[D]
2020-03-21 datetime64[D]
2020-06-15T12:00 datetime64[m]


- datetime和datetime64的互换

In [10]:
import datetime

dt = datetime.datetime(year=2020, month=6, day=1, hour=20, minute=5, second=30)
dt64 = np.datetime64(dt, 's')
print(dt64, dt64.dtype)

dt2 = dt64.astype(datetime.datetime)
print(dt2, type(dt2))

2020-06-01T20:05:30 datetime64[s]
2020-06-01 20:05:30 <class 'datetime.datetime'>


- 将指定的偏移量应用于工作日，单位天（'D'）。计算下一个工作日，如果当前日期为非工作日，默认报错。可以指定 forward 或 backward 规则来避免报错。（一个是向前取第一个有效的工作日，一个是向后取第一个有效的工作日）

In [11]:
a = np.busday_offset('2020-07-10', offsets=1)
print(a)  # 2020-07-13

a = np.busday_offset('2020-07-11', offsets=1)
print(a)

2020-07-13


ValueError: Non-business day date in busday_offset

### 数组的创建

In [12]:
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
print(a, type(a))

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]] <class 'numpy.ndarray'>


In [13]:
x = [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
y = np.array(x)
z = np.asarray(x)
x[1][2] = 2
print(x,type(x))
print(y,type(y))
print(z,type(z))

[[1, 1, 1], [1, 1, 2], [1, 1, 1]] <class 'list'>
[[1 1 1]
 [1 1 1]
 [1 1 1]] <class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]
 [1 1 1]] <class 'numpy.ndarray'>


In [14]:
x = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
y = np.array(x)
z = np.asarray(x)
w = np.asarray(x, dtype=np.int)
x[1][2] = 2
print(x,type(x),x.dtype)
print(y,type(y),y.dtype)
print(z,type(z),z.dtype)
print(w,type(w),w.dtype)

[[1 1 1]
 [1 1 2]
 [1 1 1]] <class 'numpy.ndarray'> int32
[[1 1 1]
 [1 1 1]
 [1 1 1]] <class 'numpy.ndarray'> int32
[[1 1 1]
 [1 1 2]
 [1 1 1]] <class 'numpy.ndarray'> int32
[[1 1 1]
 [1 1 2]
 [1 1 1]] <class 'numpy.ndarray'> int32


- 通过在每个坐标上执行一个函数来构造数组。

In [15]:
def f(x, y):
    return 10 * x + y

x = np.fromfunction(f, (5, 4), dtype=int)
print(x)

x = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
print(x)

x = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
print(x)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[[ True False False]
 [False  True False]
 [False False  True]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


依据 ones 和 zeros 填充方式

In [16]:
x = np.zeros(5)
print(x)
x = np.zeros([2, 3])
print(x)

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.zeros_like(x)
print(y)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]


In [17]:
x = np.ones(5)
print(x)
x = np.ones([2, 3])
print(x)
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.ones_like(x)
print(y)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


In [18]:
x = np.empty(5)
print(x)
x = np.empty((3, 2))
print(x)
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.empty_like(x)
print(y)

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0 0 0]
 [0 0 0]]


In [19]:
x = np.eye(4)
print(x)

x = np.eye(2, 3)
print(x)

x = np.identity(4)
print(x)

print(np.eye(4)==np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [20]:
x = np.arange(9).reshape((3, 3))
print(x)

print(np.diag(x)) 
print(np.diag(x, k=1))  
print(np.diag(x, k=-1))  

v = [1, 3, 5, 7]
x = np.diag(v)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]
[3 7]
[[1 0 0 0]
 [0 3 0 0]
 [0 0 5 0]
 [0 0 0 7]]


In [21]:
x = np.full((2,), 7)
print(x)

x = np.full(2, 7)
print(x)

x = np.full((2, 7), 7)
print(x)

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.full_like(x, 7)
print(y)

[7 7]
[7 7]
[[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]
[[7 7 7]
 [7 7 7]]


In [22]:
x = np.arange(5)
print(x)

x = np.arange(3, 7, 2)
print(x)  

x = np.linspace(start=0, stop=2, num=9)
print(x)  

x = np.logspace(0, 1, 5)
print(np.around(x, 2))

x = np.linspace(start=0, stop=1, num=5)
x = [10 ** i for i in x]
print(np.around(x, 2))

x = np.random.random(5)
print(x)

x = np.random.random([2, 3])
print(x)

[0 1 2 3 4]
[3 5]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 1.    1.78  3.16  5.62 10.  ]
[ 1.    1.78  3.16  5.62 10.  ]
[0.34636375 0.71700945 0.06771358 0.44471367 0.27335559]
[[0.16395922 0.94704175 0.98581685]
 [0.57268278 0.49912953 0.98882641]]


In [23]:
a = np.array([1, 2, 3, 4, 5])
print(a.shape) 
print(a.dtype)
print(a.size) 
print(a.ndim) 
print(a.itemsize)

b = np.array([[1, 2, 3], [4, 5, 6.0]])
print(b.shape) 
print(b.dtype) 
print(b.size) 
print(b.ndim)  
print(b.itemsize)  

(5,)
int32
5
1
4
(2, 3)
float64
6
2
8


- 在ndarray中所有元素必须是同一类型，否则会自动向下转换，int->float->str

In [24]:
a = np.array([1, 2, 3, 4, 5])
print(a)
b = np.array([1, 2, 3, 4, '5'])
print(b)
c = np.array([1, 2, 3, 4, 5.0])
print(c)

[1 2 3 4 5]
['1' '2' '3' '4' '5']
[1. 2. 3. 4. 5.]
