### 线性回归

#### numpy回顾
在开始操作线性回归的代码之前，先复习一下numpy的知识。必须清楚矩阵之间的乘法，即np.dot。
- 注意一维np.array的结构是(N X 1)

In [1]:
import numpy as np

In [3]:
x = np.array([[1,2,3],[3,2,1]])

In [4]:
x

array([[1, 2, 3],
       [3, 2, 1]])

In [12]:
x1 = np.insert(x,0,1,axis=1)

In [13]:
x1

array([[1, 1, 2, 3],
       [1, 3, 2, 1]])

In [26]:
x1.shape

(2, 4)

In [37]:
W = np.random.randn(4)

In [39]:
W

array([0.91081179, 0.64657748, 2.52652079, 0.71699465])

- **注意这里**

In [40]:
W.shape

(4,)

In [41]:
y = np.dot(x1,W)

In [42]:
y

array([8.76141482, 8.62058048])

In [43]:
y_pred = np.dot(x1,W)
y_pred

array([8.76141482, 8.62058048])

In [44]:
y = np.array([1,1])
y

array([1, 1])

In [45]:
error = y_pred - y
error

array([7.76141482, 7.62058048])

In [51]:
loss = np.mean(0.5*(error**2) + 0.5 * np.dot(W.T,W))
loss

33.65071631546638

In [48]:
0.5*(error**2)

array([30.11977998, 29.03662343])

In [50]:
0.5 * np.dot(W.T,W)

4.072514606897892

- **一维数组加上常数，等于数组里的每个数都加上这个是常数**

In [52]:
0.5*(error**2) + 0.5 * np.dot(W.T,W)

array([34.19229459, 33.10913804])

#### 代码实践
在代码实践中，我们将loss函数加入惩罚项以免过拟合<br><br>
代价函数公式
- $J(\theta)=\frac{1}{2 m} \sum_{i=1}^{m}\left[\left(\left(h_{\theta}\left(x^{(i)}\right)-y^{(i)}\right)^{2}+\lambda \sum_{j=1}^{n} \theta_{j}^{2}\right)\right]$


梯度更新公式
- $\theta_{j} :=\theta_{j}-a \frac{1}{m} \sum_{i=1}^{m}\left[h_{\theta}\left(x^{(i)}\right)-y^{(i)}\right] x_{j}^{(i)}+\frac{\lambda}{m} \theta_{j}$

In [53]:
import numpy as np
import pandas as pd

In [103]:
def linear(x,y,n,gamma,alpha):
    """
    liner regression
    """
    x = np.insert(x,0,1,axis=1)       # x为 m x n 的矩阵
    W = np.random.randn(x.shape[1])   # W为 n x 1 的矩阵
    for i in range(n):
        y_pred = np.dot(x,W)          # 预测值 m x 1
        error = y_pred - y            # 误差值 m x 1
        loss = np.mean(0.5 * (error ** 2) + gamma * np.dot(W.T,W))
        if i % 100 == 0:
            print('Loop is {}, loss is {}'.format(i,loss))
        gradient = np.dot(x.T,error) + gamma * W    # 梯度 n x 1
        W = W - alpha * gradient                    # 更新
    return W

#### 使用数据Bulter.csv

In [57]:
df = pd.read_csv('Butler.csv')
df

Assignment  Miles  Deliveries  Time
0           1    100           4   9.3
1           2     50           3   4.8
2           3    100           4   8.9
3           4    100           2   6.5
4           5     50           2   4.2
5           6     80           2   6.2
6           7     75           3   7.4
7           8     65           4   6.0
8           9     90           3   7.6
9          10     90           2   6.1

In [62]:
x = df[['Miles','Deliveries']].values
y = df['Time'].values
x,y

(array([[100,   4],
        [ 50,   3],
        [100,   4],
        [100,   2],
        [ 50,   2],
        [ 80,   2],
        [ 75,   3],
        [ 65,   4],
        [ 90,   3],
        [ 90,   2]], dtype=int64),
 array([9.3, 4.8, 8.9, 6.5, 4.2, 6.2, 7.4, 6. , 7.6, 6.1]))

In [64]:
x = (x - x.mean(axis=0))/x.std(axis=0)

- 不惩罚

In [104]:
linear(x,y,1000,0,0.003)

Loop is 0, loss is 29.86292874769228
Loop is 100, loss is 0.18080442614099118
Loop is 200, loss is 0.11511990883436414
Loop is 300, loss is 0.11497250778652195
Loop is 400, loss is 0.1149721750440984
Loop is 500, loss is 0.11497217428990432
Loop is 600, loss is 0.11497217428818352
Loop is 700, loss is 0.11497217428817956
Loop is 800, loss is 0.11497217428817966
Loop is 900, loss is 0.11497217428817949


array([6.7       , 1.13552477, 0.76705472])

- 带惩罚

In [106]:
linear(x,y,1000,0.0001,0.002)

Loop is 0, loss is 19.704012800910363
Loop is 100, loss is 0.4208508459252312
Loop is 200, loss is 0.12458227451782751
Loop is 300, loss is 0.11972381094764886
Loop is 400, loss is 0.11964854899896553
Loop is 500, loss is 0.11964862952303852
Loop is 600, loss is 0.11964882822339432
Loop is 700, loss is 0.11964885797273098
Loop is 800, loss is 0.11964886191908859
Loop is 900, loss is 0.11964886242982667


array([6.69993299, 1.13551442, 0.7670487 ])

#### 使用boston房价数据集

In [107]:
from sklearn.datasets import load_boston
from sklearn import datasets

In [109]:
boston = load_boston()
X = boston.data
y = boston.target
df = pd.DataFrame(X, columns=boston.feature_names)

In [110]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [111]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
dtypes: float64(13)
memory usage: 51.5 KB


数据集都有以下14个属性:

- CRIM--城镇人均犯罪率
- ZN - 占地面积超过25,000平方英尺的住宅用地比例。
- INDUS - 每个城镇非零售业务的比例。
- CHAS - Charles River虚拟变量（如果是河道，则为1;否则为0）
- NOX - 一氧化氮浓度（每千万份）
- RM - 每间住宅的平均房间数
- AGE - 1940年以前建造的自住单位比例
- DIS加权距离波士顿的五个就业中心
- RAD - 径向高速公路的可达性指数
- TAX - 每10,000美元的全额物业税率
- PTRATIO - 城镇的学生与教师比例
- B - 1000（Bk - 0.63）^ 2其中Bk是城镇黑人的比例
- LSTAT - 人口状况下降％
- MEDV - 自有住房的中位数报价, 单位1000美元

In [149]:
X = (X - X.mean(axis=0))/X.std(axis=0)

In [157]:
linear(X,y,1000,10000000,0.00000001)

Loop is 0, loss is 113737372.90802738
Loop is 100, loss is 314.47591370975096
Loop is 200, loss is 314.8553088624807
Loop is 300, loss is 314.85532105084303
Loop is 400, loss is 314.8553210511662
Loop is 500, loss is 314.8553210511662
Loop is 600, loss is 314.8553210511662
Loop is 700, loss is 314.8553210511662
Loop is 800, loss is 314.8553210511662
Loop is 900, loss is 314.8553210511662


array([ 1.14010231e-03, -1.80472727e-04,  1.67520928e-04, -2.24815856e-04,
        8.14747930e-05, -1.98596280e-04,  3.23228939e-04, -1.75186265e-04,
        1.16130864e-04, -1.77354943e-04, -2.17755579e-04, -2.36025529e-04,
        1.54985912e-04, -3.42875218e-04])

In [165]:
X_new = df[['ZN','RM','PTRATIO','LSTAT']].values

In [166]:
X_new

array([[18.   ,  6.575, 15.3  ,  4.98 ],
       [ 0.   ,  6.421, 17.8  ,  9.14 ],
       [ 0.   ,  7.185, 17.8  ,  4.03 ],
       ...,
       [ 0.   ,  6.976, 21.   ,  5.64 ],
       [ 0.   ,  6.794, 21.   ,  6.48 ],
       [ 0.   ,  6.03 , 21.   ,  7.88 ]])

In [167]:
X_new = (X_new - X_new.mean(axis=0))/X_new.std(axis=0)

In [174]:
linear(X_new,y,1000,0,0.0001)

Loop is 0, loss is 303.13005246625914
Loop is 100, loss is 13.573676639209063
Loop is 200, loss is 13.55070594529923
Loop is 300, loss is 13.55042283566844
Loop is 400, loss is 13.550416615662709
Loop is 500, loss is 13.550416478057695
Loop is 600, loss is 13.550416475012163
Loop is 700, loss is 13.550416474944754
Loop is 800, loss is 13.550416474943265
Loop is 900, loss is 13.550416474943228


array([22.53280632, -0.19686104,  3.17721164, -2.06613044, -4.13593305])